version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_home_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_home
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smart_home_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart_home_backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: smart_home
      JWT_SECRET: your-secret-key-change-this-in-production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - smart_home_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart_home_frontend
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - smart_home_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  smart_home_network:
    driver: bridge